FROM confluentinc/cp-kafka:latest

# Set the JMX Exporter version
ARG JMX_EXPORTER_VERSION=0.19.0

# Download JMX Exporter
COPY ./jmx_prometheus_javaagent-0.19.0.jar /opt/kafka/jmx_prometheus_javaagent.jar

# Add the JMX Exporter configuration file
COPY jmx-exporter-config.yml /opt/kafka/jmx-exporter-config.yml

COPY start-kafka.sh /start-kafka.sh
COPY kafka-healthcheck.sh /usr/local/bin/kafka-healthcheck.sh

CMD [ "bash","/start-kafka.sh" ]